[package]
name = "motoko-decimal"
version = "1.0.1"
description = "A fixed point Decimal type and arithmetic for Motoko."
repository = "https://github.com/DATHKA/motoko-decimal-deprecated"
keywords = [ ]
license = "MIT"

[dependencies]
core = "1.0.0"
test = "2.1.1"